config/routes.rb
Rails.application.routes.draw do

  root :to => 'welcome#index'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#create'
  get '/auth/:github/callback' => 'sessions#create'
  get 'auth/failure' => redirect('/')

  post '/item/:id/purchase' => 'items#purchase'
  
  resources :categories
  resources :comments
  resources :items do 
    resources :comments, only: [:new]
  end
  resources :users do 
    resources :comments, only: [:edit]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :purchased_items
    has_many :items, through: :purchased_items
    has_many :comments 
    has_many :items, through: :comments 

    has_secure_password

    validates :name, presence: true
    validates :email, uniqueness: true, presence: true
    validates :balance, numericality: { only_integer: true }

    def self.create_with_omniauth(auth)
        user = find_or_create_by(uid: auth['uid'], provider: auth['provider'])
        user.email = "#{auth['uid']}@#{auth['provider']}.com"
        user.password = auth['uid']
        user.name = auth['info']['name']
        user.balance = 1
        return user
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @user = User.find(session[:user_id])
        redirect_to user_path(@user.id), notice: "You do not have admin rights for that action" unless @user.admin

        @users_purchases = User.joins(:purchased_items).group("user_id").order("count(user_id) DESC")
        @users_comments = User.joins(:comments).group("user_id").order("count(user_id) DESC")

        
    end 

    def new
        @user = User.new
    end 

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user.id)
        else
            render :new
        end 
    end 

    def show
        user = User.find(params[:id])
        redirect_to '/', notice: "Forbidden action" unless session[:user_id] == user.id
        @user = user
    end 

    def edit
        user = User.find(params[:id])
        redirect_to '/', notice: "Forbidden action" unless session[:user_id] == user.id
        @user = user
    end 

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to user_path(@user)
        else 
            render :edit
        end 
    end 


    private

    def user_params
        params.require(:user).permit(:name, :email, :balance, :admin, :password)
    end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
    <p> <%= msg %></p>
    <% end %>  
<% end %>


<%= form_for @user do |u| %>

    <p> <label> Check box if you are an admin </label>
    <%= u.check_box :admin %> </p> 

    <p> <label> Name </label> <br> 
    <%= u.text_field :name %> </p> 

    <p> <label> Email </label> <br> 
    <%= u.text_field :email %> </p>

    <p> <label> How many dollars would you like to add to your account? </label> <br> 
    <%= u.number_field :balance %> </p> 

    <p> <label> Password </label> <br>
    <%= u.password_field :password %> <br> 

    <p> <%= u.submit "Save" %> </p>
<% end %> 

    

app/views/users/edit.html.erb
<h1> Edit </h1> 

<%= render 'form' %> 

app/views/users/index.html.erb
<h1> Customer Data </h1> 

<h3> Number of orders placed per customer </h3> 
<% @users_purchases.each do |u| %> 
   <li> <%= u.name %>: <%= u.purchased_items.count %> items </li> 
<% end %> 
</ul> 

<h3> Number of ratings given per customer </h3> 
<% @users_comments.each do |u| %> 
   <li> <%= u.name %>:  <%= u.comments.count %> ratings </li> 
<% end %> 
</ul> 

<br> 
<%= button_to "Back to Your details", user_path(@user.id), method: :get%>
<br> 
<%= button_to "View all items", items_path, method: :get %>

app/views/users/new.html.erb
<h1> Sign up </h1> 

<%= render 'form' %> 

<p> Already have and account? 
<%= link_to "Sign in", signin_path %> </p>

app/views/users/show.html.erb
<p> <%= flash[:notice] %> </p> 
<h1> Hello <%= @user.name %> </h1>

<p> You have $<%=@user.balance%> in your account. <p>

<%= button_to "Edit your details", edit_user_path, method: :get %> 
<br> 
<%= button_to "Place an order", items_path, method: :get %>
<br> 
<%= button_to "Log out", logout_path %>

<% if @user.admin %>
<h3> Admin Only </h3> 
<%= button_to "Customer Data", users_path, method: :get%>
<% end %> 



<h3> Past Purchases </h3> 
<% @user.purchased_items.each do |p| %>
    <% if p.item %>  
        <p> <%= p.item.name %> - <%= p.created_at.strftime("%d %b %Y") %>
    <% end %> 
<% end %> 

<h3> Past Feedback </h3> 

<% @user.comments.each do |c| %>
    <% if c.item %>  
        <p> <%=c.item.name%> (<%=c.rating %> out of 5) <%= link_to "Edit", edit_comment_path(c.id) %> 
        <%=button_to "Delete", comment_path(c.id), method: :delete %> </p>
    <% end %> 
<% end %>