config/routes.rb
Rails.application.routes.draw do

  root :to => 'welcome#index'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#create'
  get '/auth/:github/callback' => 'sessions#create'
  get 'auth/failure' => redirect('/')

  post '/item/:id/purchase' => 'items#purchase'
  
  resources :categories
  resources :comments
  resources :items do 
    resources :comments, only: [:new]
  end
  resources :users do 
    resources :comments, only: [:edit]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :category
    has_many :purchased_items
    has_many :users, through: :purchased_items
    has_many :comments
    has_many :users, through: :comments 

    validates :name, presence: true
    validates :name, uniqueness: true
    validates :description, presence: true
    validates :category_name, presence: true
    validates :price, numericality: { only_integer: true }

    scope :rated_above, -> (num) { joins(:comments).where('rating > ?', num)}

    def category_name=(name)
        self.category = Category.find_or_create_by(name: name)
    end
    
    def category_name
        self.category ? self.category.name : nil
    end

    def comments_count
        comments.count
    end 

    def average_rating
        if comments.count > 0
            total = 0 
            comments.each do |c|
            total += c.rating 
            end 
            total / comments_count
        else
            0 
        end 
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :require_login
    before_action :admin_rights
    skip_before_action :admin_rights, only: [:index, :show, :purchase]

    def index
        @user = User.find(session[:user_id])
        @items = Item.all
        @categories = Category.all
        @highrated = Item.rated_above(4).uniq
        @popular_items = Item.joins(:purchased_items).group("item_id").order("count(item_id) DESC").first(3)
    end

    def new
        @item = Item.new
        @categories = Category.all
    end 

    def create
        @item = Item.new(item_params)
        if @item.save
            redirect_to item_path(@item.id), notice: "New Item Added"
        else 
            render :new
        end 
    end 

    def show
        @user = User.find(session[:user_id])
        @item = Item.find(params[:id])
        @comments = @item.comments
    end 

    def edit
        @item = Item.find(params[:id])        
    end

    def update
        @item = Item.find(params[:id])
        if @item.update(item_params)
            redirect_to item_path(@item)
        else 
            render :edit
        end
    end 

    def destroy
        @item = Item.find(params[:id])
        @item.destroy
        redirect_to items_path, notice: "You deleted the item: #{@item.name}"
    end

    def purchase
        item = Item.find(params[:id])
        user = User.find(session[:user_id])
        if item.price < user.balance
            user.balance -= item.price
            user.save
            purchase = PurchasedItem.new(user_id: user.id, item_id: item.id)
            purchase.save
            redirect_to user_path(user)
        else 
            redirect_to item_path(item.id), notice: "You do not have enough in your account for this item "
        end
    end


    private

    def item_params
        params.require(:item).permit(:name, :description, :price, :points, :category_name)
    end

    def require_login
        redirect_to '/', notice: "Please sign in first" unless session.include? :user_id
    end

    def admin_rights
        @user = User.find(session[:user_id])
        redirect_to user_path(@user.id), notice: "You do not have admin rights for that action" unless @user.admin
    end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<% if @item.errors.any? %>
    <% @item.errors.full_messages.each do |msg| %>
    <p> <%= msg %></p>
    <% end %>  
<% end %>



<%= form_for @item do |i| %>

    <p> <label> Name </label> <br> 
    
    <%= i.text_field :name %> </p> 

    <p> <label> Description </label> <br> 
    <%= i.text_area :description %> </p>

    <p> <label> Price ($) </label> <br> 
    <%= i.number_field :price %> </p> 
    
    <p> <label> Category </label> <br>
    <%= i.text_field :category_name, list: "categories_autocomplete" %>
    <datalist id="categories_autocomplete">
    <% Category.all.each do |category| %>
      <option value="<%= category.name %>">
    <% end %>
    </datalist>

    <p> <%= i.submit "Save" %> </p>
<% end %> 

app/views/items/edit.html.erb
<h1> Editing <%=@item.name%> </h1> 
<p> <%= flash[:notice] %> </p> 
 
<%= render 'form' %> 

app/views/items/index.html.erb
<h1> Showing all items </h1> 
<p> <%= flash[:notice] %> </p> 

    <br> 

    <h2> Highly Rated (4 stars and above) </h2> 
    <% @highrated.each do |i| %> 
        <p> <%= link_to  i.name, item_path(i.id) %> ($<%=i.price %>) </p> 
    <% end %>
    
    <br> 

    <h2> Top 3 most popular </h2> 
    <% @popular_items.each do |i| %> 
       <p> <%= link_to  i.name, item_path(i.id) %>  (<%= i.purchased_items.count %> purchases) </p> 
    <% end %> 
    
    <br> 

    <h2> All items by Category </h2> 
    <% @categories.each do |c| %> 
        <h3> <div style="float: left; width: auto;"> <%= c.name %>  </div> </h3> 
            <% if c.items.count < 1 && @user.admin %>
                <%= button_to "Remove Category", category_path(c.id), method: :delete%>
            <% end %> 
            <br> 
            <% c.items.each do |i| %> 
                <p> <%= link_to  i.name, item_path(i.id) %> ($<%=i.price %>) </p> 
            <% end %>  
    <% end %> 

<br> 
<br> 

<%= button_to "Back to Your details", user_path(@user.id), method: :get%>
<br> 
<%= button_to "Log out", logout_path %>
<br> 
<% if @user.admin %>
<h3> Admin Only </h3> 
<%= button_to "Add a new item", new_item_path, method: :get%>
<% end %> 
 

app/views/items/new.html.erb
<h1> Adding a new Item </h1> 
<p> <%= flash[:notice] %> </p> 

<%= render 'form' %> 

app/views/items/show.html.erb
<h1> <%= @item.name %> </h1> 
<p> <%= flash[:notice] %> </p> 

<p> Description: <%=@item.description %> </p> 

<p> Category: <%=@item.category_name %> </p> 

<p> Price: $<%=@item.price %> </p> 


<%= button_to "Purchase", action: "purchase"%> 
<br> 
<%=button_to "< Back to all items", items_path, method: :get%> 
<br> 
<%= button_to "<< Back to your details", user_path(@user.id), method: :get%>

<h3> Ratings and Feedback 
<%= @item.average_rating %> out of 5 </h3> 
<%= @item.comments_count %> customer reviews

<ul> 
<% @comments.each do |c| %> 
    <li> <%= c.rating %> out of 5 
    <%= c.decription %> </li> 
<% end %> 
</ul> 
<br> 
<%=button_to "Leave a review", new_item_comment_path(@item.id), method: :get%> 
<br> 


<% if @user.admin %>
<h3> Admin Only </h3> 
<%=button_to "Edit", edit_item_path(@item.id), method: :get%> 
<br> 
<%=button_to "Delete", item_path(@item.id), method: :delete%> 
<% end %> 